#!/usr/bin/env python3

import argparse
import json
import sys
from pathlib import Path

def parse(file, name):
    print("// This file was generated by " + sys.argv[0])
    print("#pragma once\n")
    print("struct Lebedev_Point {\n\
    double theta;\n\
    double phi;\n\
    double w;\n\
};\n")
    print("static std::vector<Lebedev_Point> " + name + " = {")
    for line in file:
        try:
            theta, phi, w = line.strip().split()
        except Exception as err:
            sys.stderr.write(f"Error parsing line \"{line}\": {err}.\n")
            sys.exit(1)
        print(" " * 4 + "{ " + f"{theta}, {phi}, {w}" " },")
    print("};")

def main():
    parser = argparse.ArgumentParser(
        description="Convert a Lebedev data file into a C++ static object."
    )
    parser.add_argument(
        "file",
        help="Path to the file containing the data."
    )
    args = parser.parse_args()

    try:
        with open(args.file, "r") as file_handle:
            parse(file_handle, Path(args.file).stem)
    except Exception as err:
        sys.stderr.write(f"Error reading file: {err}\n")
        sys.exit(1)

if __name__ == "__main__":
    main()
