// clang++ main.cpp -o main

#include <vector>

void compute_gauss_legendre(int n, std::vector<double>& x, std::vector<double>& w) {
    x.resize(n);
    w.resize(n);
    const double eps = 1e-14;
    int m = (n + 1) / 2;
    for (int i = 0; i < m; ++i) {
        double z = std::cos(M_PI * (i + 0.75) / (n + 0.5));
        double pp, p1, p2, p3;
        do {
            p1 = 1.0;
            p2 = 0.0;
            for (int j = 0; j < n; ++j) {
                p3 = p2;
                p2 = p1;
                p1 = ((2.0 * j + 1.0) * z * p2 - j * p3) / (j + 1.0);
            }
            pp = n * (z * p1 - p2) / (z * z - 1.0);
            z = z - p1 / pp;
        } while (std::abs(p1 / pp) > eps);

        x[i] = -z;
        x[n - 1 - i] = z;
        w[i] = 2.0 / ((1.0 - z * z) * pp * pp);
        w[n - 1 - i] = w[i];
    }
}

int main() {
    std::vector<double> x, w;
    int n = 4;
    compute_gauss_legendre(n, x, w);
    
    std::printf("// This file was generated by tool/gauss_legendre/main.cpp\n");
    std::printf("#pragma once\n\n");
    std::printf("struct Gauss_Legendre_Point {\n    double x;\n    double w;\n};\n\n");
    std::printf("static std::vector<Gauss_Legendre_Point> gauss_legendre_%d {\n", n);
    for (int i = 0; i < n; ++i) {
        std::printf("    { %.15f, %.15f },\n", x[i], w[i]);
    }
    std::printf("};\n");
    return 0;
}